import type { GrammarRule, Vocabulary, Course, Flashcard } from "@/types";

export const GRAMMAR_RULES_FALLBACK: GrammarRule[] = [
  {
    id: 1,
    title: "German Articles: der, die, das",
    level: "A1",
    category: "articles",
    explanation: "Every German noun has a grammatical gender: masculine (der), feminine (die), or neuter (das). The article must always match the gender of the noun. Plural nouns always use 'die' regardless of gender.",
    formula: "der (m) · die (f) · das (n) · die (plural)",
    examples: [
      { german: "der Mann — the man", english: "masculine noun" },
      { german: "die Frau — the woman", english: "feminine noun" },
      { german: "das Kind — the child", english: "neuter noun" },
      { german: "die Männer — the men", english: "plural always uses 'die'" },
    ],
    tips: [
      "Always learn every noun WITH its article: 'der Tisch', not just 'Tisch'.",
      "Nouns ending in -ung, -heit, -keit, -schaft are always feminine (die).",
      "Nouns ending in -chen or -lein are always neuter (das): das Mädchen.",
      "Days, months, and seasons are masculine: der Montag, der Januar, der Sommer.",
    ],
  },
  {
    id: 2,
    title: "Personal Pronouns (Personalpronomen)",
    level: "A1",
    category: "pronouns",
    explanation: "German personal pronouns replace nouns in sentences. In the nominative (subject) case they are: ich, du, er/sie/es, wir, ihr, sie/Sie.",
    formula: "ich · du · er/sie/es · wir · ihr · sie · Sie (formal)",
    examples: [
      { german: "Ich bin Student.", english: "I am a student." },
      { german: "Du sprichst gut Deutsch.", english: "You speak German well." },
      { german: "Er kommt aus Berlin.", english: "He comes from Berlin." },
      { german: "Wir lernen zusammen.", english: "We are learning together." },
    ],
    tips: [
      "Sie (capital S) is the formal 'you' — use it with strangers and in professional settings.",
      "sie (lowercase s) means 'she' OR 'they' — context tells you which.",
      "In the Goethe exam, always use 'Sie' when writing to someone you don't know.",
    ],
  },
  {
    id: 3,
    title: "Present Tense (Präsens) — Regular Verbs",
    level: "A1",
    category: "tenses",
    explanation: "The present tense (Präsens) is used for current actions, habits, and general facts. Regular verbs follow a predictable conjugation pattern by removing the infinitive -en ending and adding personal endings.",
    formula: "stem + -e / -st / -t / -en / -t / -en",
    examples: [
      { german: "ich lerne — I learn / I am learning", english: "1st person singular" },
      { german: "du lernst — you learn", english: "2nd person singular" },
      { german: "er/sie/es lernt — he/she/it learns", english: "3rd person singular" },
      { german: "wir lernen — we learn", english: "1st person plural" },
    ],
    tips: [
      "Verbs whose stem ends in -t or -d add an extra -e- for pronunciation: du arbeitest, er arbeitet.",
      "The Präsens also covers the English present continuous: 'ich lerne' = both 'I learn' and 'I am learning'.",
      "Most A1 exam tasks require you to conjugate regular verbs correctly.",
    ],
  },
  {
    id: 4,
    title: "Verb 'sein' (to be)",
    level: "A1",
    category: "verbs",
    explanation: "'Sein' is one of the most important irregular verbs in German. It is used to describe identity, origin, professions, and characteristics. It is also used to form the perfect tense of movement and change-of-state verbs.",
    formula: "ich bin · du bist · er/sie/es ist · wir sind · ihr seid · sie/Sie sind",
    examples: [
      { german: "Ich bin Lehrerin.", english: "I am a teacher." },
      { german: "Du bist müde.", english: "You are tired." },
      { german: "Wir sind aus Deutschland.", english: "We are from Germany." },
      { german: "Er ist nach Hause gegangen.", english: "He has gone home. (Perfekt with sein)" },
    ],
    tips: [
      "No article is needed after 'sein' for professions: 'Ich bin Arzt' (not 'ein Arzt').",
      "Movement verbs use 'sein' in perfect tense: gehen, kommen, fahren, fliegen.",
    ],
  },
  {
    id: 5,
    title: "Verb 'haben' (to have)",
    level: "A1",
    category: "verbs",
    explanation: "'Haben' is used to express possession and is the auxiliary verb for forming the Perfekt (past tense) of most German verbs.",
    formula: "ich habe · du hast · er/sie/es hat · wir haben · ihr habt · sie/Sie haben",
    examples: [
      { german: "Ich habe ein Auto.", english: "I have a car." },
      { german: "Sie hat Hunger.", english: "She is hungry. (lit: She has hunger)" },
      { german: "Wir haben gelernt.", english: "We have learned. (Perfekt)" },
      { german: "Hast du Zeit?", english: "Do you have time?" },
    ],
    tips: [
      "German uses 'haben' for states that English expresses with 'to be': Hunger haben (to be hungry), Durst haben (to be thirsty).",
      "Most verbs use 'haben' in Perfekt — only movement/change verbs use 'sein'.",
    ],
  },
  {
    id: 6,
    title: "Negation: nicht and kein",
    level: "A1",
    category: "word_order",
    explanation: "'Nicht' negates verbs, adjectives, and specific nouns. 'Kein' negates nouns that take an indefinite article (ein/eine) or no article at all. They are NOT interchangeable.",
    formula: "nicht + verb/adjective · kein-/keine/kein + noun",
    examples: [
      { german: "Ich lerne nicht.", english: "I am not learning." },
      { german: "Das ist nicht gut.", english: "That is not good." },
      { german: "Ich habe kein Auto.", english: "I don't have a car." },
      { german: "Er hat keine Zeit.", english: "He has no time." },
    ],
    tips: [
      "'Kein' replaces 'ein': Ich habe ein Buch → Ich habe kein Buch.",
      "'Nicht' goes before adjectives and after time expressions: 'Er kommt heute nicht.'",
      "In the Goethe exam, using 'nicht' vs 'kein' correctly is tested in Schreiben.",
    ],
  },
  {
    id: 7,
    title: "W-Questions (W-Fragen)",
    level: "A1",
    category: "word_order",
    explanation: "W-questions use question words beginning with W- to ask for specific information. The question word comes first, followed by the verb, then the subject.",
    formula: "W-Wort + Verb + Subjekt + ...",
    examples: [
      { german: "Wie heißt du?", english: "What is your name?" },
      { german: "Wo wohnst du?", english: "Where do you live?" },
      { german: "Woher kommst du?", english: "Where are you from?" },
      { german: "Wann beginnt der Kurs?", english: "When does the course begin?" },
    ],
    tips: [
      "Key W-words: Wer (who), Was (what), Wo (where), Woher (from where), Wohin (to where), Wann (when), Wie (how), Warum (why), Wie viel (how much).",
      "The verb always takes the 2nd position in a W-question.",
    ],
  },
  {
    id: 8,
    title: "Accusative Case (Akkusativ)",
    level: "A1",
    category: "cases",
    explanation: "The accusative case marks the direct object of a sentence — the thing being acted upon. Only masculine articles change in the accusative: 'der' → 'den', 'ein' → 'einen'. Feminine, neuter, and plural stay the same.",
    formula: "der→den / ein→einen (masculine only)",
    examples: [
      { german: "Ich kaufe den Apfel.", english: "I buy the apple. (masc.)" },
      { german: "Er sieht eine Frau.", english: "He sees a woman. (fem. — no change)" },
      { german: "Wir haben das Buch.", english: "We have the book. (neut. — no change)" },
      { german: "Ich brauche keinen Stift.", english: "I don't need a pen." },
    ],
    tips: [
      "Only masculine (der/ein) changes in Akkusativ — remember 'den/einen'.",
      "Verbs like haben, sehen, kaufen, brauchen, essen, trinken take accusative objects.",
      "Accusative prepositions: durch, für, gegen, ohne, um — these always trigger accusative.",
    ],
  },
  {
    id: 9,
    title: "Modal Verbs (Modalverben)",
    level: "A2",
    category: "verbs",
    explanation: "Modal verbs express ability, permission, obligation, or desire. They are always paired with an infinitive which goes to the end of the sentence. They have irregular conjugations in singular forms.",
    formula: "Modal Verb (position 2) + ... + Infinitive (end)",
    examples: [
      { german: "Ich kann Deutsch sprechen.", english: "I can speak German." },
      { german: "Du musst jeden Tag üben.", english: "You must practice every day." },
      { german: "Darf ich eine Frage stellen?", english: "May I ask a question?" },
      { german: "Wir sollen um 9 Uhr da sein.", english: "We are supposed to be there at 9." },
    ],
    tips: [
      "The 6 modal verbs: können (can), müssen (must), wollen (want), sollen (should/supposed to), dürfen (may/allowed to), mögen/möchten (like/would like).",
      "In the ich and er/sie/es forms, modal verbs often lose their umlaut: können → ich kann.",
      "Past tense of modals uses Präteritum: ich konnte, ich musste, ich wollte.",
    ],
  },
  {
    id: 10,
    title: "Perfect Tense (Perfekt)",
    level: "A2",
    category: "tenses",
    explanation: "The Perfekt is the most common past tense in spoken German. It is formed with the auxiliary verb 'haben' or 'sein' in the present tense, plus the past participle (Partizip II) of the main verb at the end.",
    formula: "haben/sein (position 2) + ... + Partizip II (end)",
    examples: [
      { german: "Ich habe Deutsch gelernt.", english: "I (have) learned German." },
      { german: "Sie hat das Buch gelesen.", english: "She (has) read the book." },
      { german: "Er ist nach Hause gegangen.", english: "He (has) gone home." },
      { german: "Wir sind nach Berlin gefahren.", english: "We (have) driven to Berlin." },
    ],
    tips: [
      "Regular Partizip II: ge- + stem + -t (lernen → gelernt, kaufen → gekauft).",
      "Irregular Partizip II must be memorized: schreiben → geschrieben, sprechen → gesprochen.",
      "Use 'sein' with movement verbs (gehen, fahren, fliegen) and change-of-state verbs (aufwachen, sterben).",
      "Verbs with inseparable prefixes (be-, ver-, er-) don't get 'ge-': verstehen → verstanden.",
    ],
  },
  {
    id: 11,
    title: "Dative Case (Dativ)",
    level: "A2",
    category: "cases",
    explanation: "The dative case marks the indirect object — the recipient or beneficiary of an action. Articles change for all genders in the dative: dem/der/dem/den.",
    formula: "dem (m/n) · der (f) · den+n (plural)",
    examples: [
      { german: "Ich gebe dem Mann das Buch.", english: "I give the book to the man." },
      { german: "Er hilft der Frau.", english: "He helps the woman." },
      { german: "Das gehört meinem Bruder.", english: "That belongs to my brother." },
      { german: "Ich danke meinen Eltern.", english: "I thank my parents." },
    ],
    tips: [
      "Dative verbs (always dative, no accusative): helfen, gehören, danken, gefallen, glauben, folgen.",
      "Dative prepositions: aus, bei, mit, nach, seit, von, zu, gegenüber, außer — always trigger dative.",
      "Plural dative adds -n to the noun if it doesn't already end in -n: die Männer → den Männern.",
    ],
  },
  {
    id: 12,
    title: "Separable Verbs (Trennbare Verben)",
    level: "A2",
    category: "verbs",
    explanation: "Many German verbs have a separable prefix that splits off and goes to the end of the main clause in present tense and imperative. The prefix carries the main meaning change.",
    formula: "Verb stem (position 2) + ... + Prefix (end)",
    examples: [
      { german: "Ich stehe um 7 Uhr auf.", english: "I get up at 7 o'clock. (aufstehen)" },
      { german: "Der Zug kommt um 15 Uhr an.", english: "The train arrives at 3pm. (ankommen)" },
      { german: "Sie ruft ihre Mutter an.", english: "She calls her mother. (anrufen)" },
      { german: "Wann fährt der Bus ab?", english: "When does the bus depart? (abfahren)" },
    ],
    tips: [
      "Common separable prefixes: ab-, an-, auf-, aus-, ein-, mit-, nach-, vor-, zu-, zurück-.",
      "In Partizip II: the 'ge-' goes between prefix and stem: aufgestanden, angerufen.",
      "Inseparable prefixes (be-, ge-, er-, ver-, zer-, miss-) NEVER separate.",
    ],
  },
  {
    id: 13,
    title: "Subordinate Clauses (Nebensätze): weil, dass, wenn",
    level: "A2",
    category: "word_order",
    explanation: "In subordinate clauses introduced by conjunctions like 'weil' (because), 'dass' (that), 'wenn' (when/if), the conjugated verb moves to the VERY END of the clause.",
    formula: "..., conjunction + subject + ... + VERB (end)",
    examples: [
      { german: "Ich lerne Deutsch, weil ich in Deutschland arbeiten möchte.", english: "I learn German because I want to work in Germany." },
      { german: "Er sagt, dass er müde ist.", english: "He says that he is tired." },
      { german: "Wenn ich Zeit habe, lese ich gern.", english: "When I have time, I like to read." },
      { german: "Ich bleibe zu Hause, weil es regnet.", english: "I stay at home because it is raining." },
    ],
    tips: [
      "The verb-end rule applies to ALL subordinating conjunctions: weil, dass, wenn, ob, als, obwohl, damit, bevor, nachdem...",
      "If the subordinate clause comes first, the main clause starts with the verb (V1): 'Weil er krank ist, kommt er nicht.'",
      "Modal verbs: both go to the end — infinitive before modal: '...weil er kommen muss.'",
    ],
  },
  {
    id: 14,
    title: "Adjective Endings (Adjektivdeklination)",
    level: "A2",
    category: "adjectives",
    explanation: "When an adjective comes before a noun, it must take an ending that reflects the noun's gender, case, and whether a definite/indefinite/no article is used.",
    formula: "Article + Adjective(-e/-en/-em/-er/-es) + Noun",
    examples: [
      { german: "der alte Mann (nom. masc.)", english: "the old man" },
      { german: "eine alte Frau (nom. fem.)", english: "an old woman" },
      { german: "das alte Haus (nom. neut.)", english: "the old house" },
      { german: "Ich sehe den alten Mann. (acc. masc.)", english: "I see the old man." },
    ],
    tips: [
      "After definite articles (der/die/das/die), use -e (nominative sing.) or -en (everything else).",
      "After indefinite articles (ein/eine/ein), the adjective carries the gender signal: ein alter Mann, eine alte Frau.",
      "Predicate adjectives (after sein/werden) never take endings: 'Der Mann ist alt.'",
    ],
  },
  {
    id: 15,
    title: "Two-way Prepositions (Wechselpräpositionen)",
    level: "B1",
    category: "cases",
    explanation: "Nine prepositions can take either accusative (movement/direction toward a destination) or dative (location/static position). The key question: Is something MOVING somewhere (Akkusativ) or LOCATED somewhere (Dativ)?",
    formula: "Wohin? (where to?) → Akkusativ | Wo? (where?) → Dativ",
    examples: [
      { german: "Ich gehe in die Schule. (Akk — going INTO)", english: "I go into the school." },
      { german: "Ich bin in der Schule. (Dat — located IN)", english: "I am in the school." },
      { german: "Er legt das Buch auf den Tisch. (Akk)", english: "He puts the book onto the table." },
      { german: "Das Buch liegt auf dem Tisch. (Dat)", english: "The book is lying on the table." },
    ],
    tips: [
      "The 9 two-way prepositions: an, auf, hinter, in, neben, über, unter, vor, zwischen.",
      "Action verbs like legen, stellen, hängen, setzen → Akkusativ (destination).",
      "State verbs like liegen, stehen, hängen, sitzen → Dativ (location).",
      "Contractions: in + dem = im, in + das = ins, an + dem = am, an + das = ans.",
    ],
  },
  {
    id: 16,
    title: "Simple Past (Präteritum) — Narrative Past",
    level: "B1",
    category: "tenses",
    explanation: "The Präteritum is used in written German for storytelling and narrative. In spoken German, only 'sein', 'haben', and modal verbs commonly use Präteritum; other verbs use Perfekt in conversation.",
    formula: "Regular: stem + -te/-test/-te/-ten/-tet/-ten",
    examples: [
      { german: "Ich war gestern krank.", english: "I was sick yesterday." },
      { german: "Er hatte keine Zeit.", english: "He had no time." },
      { german: "Sie konnte nicht kommen.", english: "She could not come." },
      { german: "Der Zug fuhr um 10 Uhr ab.", english: "The train departed at 10. (irregular)" },
    ],
    tips: [
      "Learn sein/haben/können/müssen/wollen in Präteritum — you'll use them constantly.",
      "Strong (irregular) verbs change their stem vowel: fahren → fuhr, schreiben → schrieb, sehen → sah.",
      "In the Goethe B1 Schreiben exam, you may need to use Präteritum in formal texts.",
    ],
  },
  {
    id: 17,
    title: "Passive Voice (Passiv)",
    level: "B1",
    category: "tenses",
    explanation: "The passive voice (Vorgangspassiv) shifts the focus from the doer to the action itself. It is formed with 'werden' + Partizip II. The agent (doer) can be added with 'von + Dativ'.",
    formula: "werden (conjugated) + ... + Partizip II (end)",
    examples: [
      { german: "Das Haus wird gebaut.", english: "The house is being built." },
      { german: "Die Prüfung wird von den Studenten geschrieben.", english: "The exam is written by the students." },
      { german: "Das Auto wurde repariert.", english: "The car was repaired. (past passive)" },
      { german: "Das Lied wird oft gesungen.", english: "The song is often sung." },
    ],
    tips: [
      "Passive is common in formal writing, instructions, and news — important for B1 Lesen.",
      "Only transitive verbs (verbs that take an accusative object) can be made passive.",
      "State passive (Zustandspassiv) uses 'sein' + Partizip II: 'Die Tür ist geöffnet.'",
    ],
  },
  {
    id: 18,
    title: "Konjunktiv II — würde + Infinitiv",
    level: "B1",
    category: "verbs",
    explanation: "Konjunktiv II expresses unreal conditions, polite requests, wishes, and hypotheticals. The simplest form uses 'würde' + infinitive, similar to 'would' in English.",
    formula: "würde + ... + Infinitiv (end) | OR: stem + umlaut + -te endings",
    examples: [
      { german: "Ich würde gern Deutsch lernen.", english: "I would like to learn German." },
      { german: "Könnten Sie mir bitte helfen?", english: "Could you please help me?" },
      { german: "Wenn ich Zeit hätte, würde ich reisen.", english: "If I had time, I would travel." },
      { german: "Das wäre schön.", english: "That would be nice." },
    ],
    tips: [
      "For polite requests in the exam, use: Könnten Sie...? Würden Sie...? Ich hätte gern...",
      "Common Konjunktiv II forms to learn: wäre (sein), hätte (haben), könnte (können), müsste (müssen), würde (werden).",
      "Wenn-Satz + Hauptsatz: 'Wenn ich reich wäre, würde ich viel reisen.'",
    ],
  },
  {
    id: 19,
    title: "Relative Clauses (Relativsätze)",
    level: "B1",
    category: "word_order",
    explanation: "Relative clauses describe or identify a noun. They are introduced by a relative pronoun (der, die, das, die) that agrees in gender and number with the noun it refers to, but takes the case required by its role in the relative clause.",
    formula: "Noun + [, Rel.pronoun + ... + Verb (end)]",
    examples: [
      { german: "Das ist der Mann, der Deutsch spricht.", english: "That is the man who speaks German." },
      { german: "Die Frau, die ich kenne, ist Ärztin.", english: "The woman (whom) I know is a doctor." },
      { german: "Das Buch, das ich lese, ist interessant.", english: "The book (that) I am reading is interesting." },
      { german: "Die Studenten, mit denen ich lerne, sind sehr fleißig.", english: "The students with whom I study are very diligent." },
    ],
    tips: [
      "The relative pronoun matches the GENDER/NUMBER of the noun it refers to.",
      "The CASE of the relative pronoun depends on its grammatical function in the relative clause.",
      "With prepositions: preposition comes before the relative pronoun: 'der Mann, mit dem ich arbeite'.",
    ],
  },
  {
    id: 20,
    title: "Infinitive with 'zu'",
    level: "B1",
    category: "verbs",
    explanation: "Many German expressions and verbs are followed by an infinitive with 'zu'. With separable verbs, 'zu' is inserted between the prefix and the stem.",
    formula: "... + zu + Infinitiv (end) | separable: prefix + zu + stem",
    examples: [
      { german: "Es ist wichtig, jeden Tag zu üben.", english: "It is important to practice every day." },
      { german: "Ich versuche, mehr zu lesen.", english: "I try to read more." },
      { german: "Er hat vergessen, zurückzurufen.", english: "He forgot to call back. (separable: zurückrufen)" },
      { german: "Sie hat keine Lust, früh aufzustehen.", english: "She doesn't feel like getting up early." },
    ],
    tips: [
      "Common expressions with zu-infinitive: Es ist (un)möglich zu..., Ich habe vor zu..., Es macht Spaß zu...",
      "Verbs that always take zu + infinitive: versuchen, vergessen, beginnen, hoffen, empfehlen, planen.",
      "Modal verbs NEVER take 'zu': Ich kann kommen (NOT: zu kommen).",
    ],
  },
  {
    id: 21,
    title: "Genitive Case (Genitiv)",
    level: "B1",
    category: "cases",
    explanation: "The genitive case expresses possession or relationship between nouns. It answers the question 'Whose?'. In spoken German it is often replaced by 'von + Dativ', but it is important for written and formal German.",
    formula: "des/eines+s (m/n) · der/einer (f) · der/einer (pl)",
    examples: [
      { german: "Das ist das Haus meines Vaters.", english: "That is my father's house." },
      { german: "Die Farbe des Autos ist rot.", english: "The color of the car is red." },
      { german: "während des Sommers", english: "during the summer (gen. preposition)" },
      { german: "trotz des schlechten Wetters", english: "despite the bad weather" },
    ],
    tips: [
      "Masculine and neuter nouns add -(e)s in genitive: der Mann → des Mannes.",
      "Genitive prepositions: wegen, trotz, während, (an)statt, aufgrund, innerhalb, außerhalb.",
      "In B1 Schreiben, using genitive correctly shows advanced grammar knowledge.",
    ],
  },
  {
    id: 22,
    title: "Comparative and Superlative (Komparativ & Superlativ)",
    level: "A2",
    category: "adjectives",
    explanation: "German adjectives form comparatives with -er and superlatives with am...-sten (predicate) or dem/den...-sten (attributive). Many common adjectives add an umlaut.",
    formula: "Adj + -er (comparative) · am + Adj + -sten (superlative)",
    examples: [
      { german: "schnell → schneller → am schnellsten", english: "fast → faster → fastest" },
      { german: "alt → älter → am ältesten", english: "old → older → oldest" },
      { german: "gut → besser → am besten", english: "good → better → best (irregular)" },
      { german: "Sie ist die klügste Studentin.", english: "She is the smartest student. (attributive superlative)" },
    ],
    tips: [
      "Irregular comparatives: gut/besser/am besten, viel/mehr/am meisten, gern/lieber/am liebsten.",
      "Adjectives ending in -t, -d, -s, -ß, -sch, -z add -est- in superlative: alt → am ältesten.",
      "Comparative in sentences: 'Er ist größer als ich.' (than = als)",
    ],
  },
  {
    id: 23,
    title: "Prepositions with Accusative",
    level: "A2",
    category: "cases",
    explanation: "Six prepositions ALWAYS take the accusative case, regardless of context. These must be memorised.",
    formula: "durch · für · gegen · ohne · um · bis",
    examples: [
      { german: "Ich kaufe das Geschenk für meinen Vater.", english: "I buy the gift for my father." },
      { german: "Wir gehen durch den Park.", english: "We walk through the park." },
      { german: "Er fährt gegen die Wand.", english: "He drives into/against the wall." },
      { german: "Sie kommt ohne ihren Mann.", english: "She comes without her husband." },
    ],
    tips: [
      "Memory trick: 'durch für gegen ohne um bis' — learn them as a list.",
      "These always take accusative: 'für den Mann, durch den Wald, um das Haus'.",
      "Bis is usually combined with another preposition: bis zum Bahnhof (bis + zu + Dativ).",
    ],
  },
  {
    id: 24,
    title: "Prepositions with Dative",
    level: "A2",
    category: "cases",
    explanation: "Nine prepositions ALWAYS take the dative case. These must be memorised as a group.",
    formula: "aus · bei · mit · nach · seit · von · zu · gegenüber · außer",
    examples: [
      { german: "Ich fahre mit dem Bus.", english: "I travel by bus." },
      { german: "Ich wohne bei meiner Freundin.", english: "I live at my friend's place." },
      { german: "Seit einem Jahr lerne ich Deutsch.", english: "I have been learning German for a year." },
      { german: "Die Post ist gegenüber dem Bahnhof.", english: "The post office is opposite the train station." },
    ],
    tips: [
      "Memory trick: 'aus bei mit nach seit von zu gegenüber außer'.",
      "Contractions: bei + dem = beim, von + dem = vom, zu + dem = zum, zu + der = zur.",
      "Seit + present tense in German = English present perfect: 'Ich lerne seit 2 Jahren Deutsch.' = 'I have been learning German for 2 years.'",
    ],
  },
  {
    id: 25,
    title: "Word Order: Verb in Second Position (V2)",
    level: "A1",
    category: "word_order",
    explanation: "In German main clauses, the conjugated verb ALWAYS occupies the second position, regardless of what comes first. This is the fundamental V2 rule of German word order.",
    formula: "[Element 1] + VERB + [Subject (if not first)] + ...",
    examples: [
      { german: "Ich lerne jeden Tag Deutsch.", english: "I learn German every day." },
      { german: "Jeden Tag lerne ich Deutsch.", english: "Every day I learn German. (time expression first)" },
      { german: "Deutsch lerne ich jeden Tag.", english: "German I learn every day. (object first, for emphasis)" },
      { german: "Heute gehe ich nicht in die Schule.", english: "Today I am not going to school." },
    ],
    tips: [
      "The verb is ALWAYS in position 2 in a main clause — no exceptions.",
      "What goes in position 1 can vary for emphasis, but the verb stays in position 2.",
      "In yes/no questions, the verb moves to position 1: 'Lernst du Deutsch?'",
    ],
  },
];

export const VOCABULARY_FALLBACK: Vocabulary[] = [
  // A1 - Greetings & Basics
  { id: 101, german_word: "Hallo", english_translation: "Hello", word_type: "phrase", level: "A1", example_sentence_de: "Hallo! Wie geht es dir?", example_sentence_en: "Hello! How are you?" },
  { id: 102, german_word: "danke", english_translation: "thank you", word_type: "phrase", level: "A1", example_sentence_de: "Danke schön!", example_sentence_en: "Thank you very much!" },
  { id: 103, german_word: "bitte", english_translation: "please / you're welcome", word_type: "phrase", level: "A1", example_sentence_de: "Bitte schön!", example_sentence_en: "You're welcome!" },
  { id: 104, german_word: "Entschuldigung", english_translation: "excuse me / sorry", word_type: "phrase", level: "A1", example_sentence_de: "Entschuldigung, wo ist der Bahnhof?", example_sentence_en: "Excuse me, where is the train station?" },
  // A1 - People & Family
  { id: 105, german_word: "Mann", article: "der", english_translation: "man / husband", word_type: "noun", level: "A1", example_sentence_de: "Der Mann heißt Thomas.", example_sentence_en: "The man's name is Thomas." },
  { id: 106, german_word: "Frau", article: "die", english_translation: "woman / wife / Mrs.", word_type: "noun", level: "A1", example_sentence_de: "Die Frau arbeitet als Lehrerin.", example_sentence_en: "The woman works as a teacher." },
  { id: 107, german_word: "Kind", article: "das", english_translation: "child", word_type: "noun", level: "A1", example_sentence_de: "Das Kind spielt im Park.", example_sentence_en: "The child plays in the park." },
  { id: 108, german_word: "Familie", article: "die", english_translation: "family", word_type: "noun", level: "A1", example_sentence_de: "Meine Familie wohnt in Berlin.", example_sentence_en: "My family lives in Berlin." },
  { id: 109, german_word: "Mutter", article: "die", english_translation: "mother", word_type: "noun", level: "A1", example_sentence_de: "Meine Mutter kocht sehr gut.", example_sentence_en: "My mother cooks very well." },
  { id: 110, german_word: "Vater", article: "der", english_translation: "father", word_type: "noun", level: "A1", example_sentence_de: "Mein Vater arbeitet bei einer Bank.", example_sentence_en: "My father works at a bank." },
  { id: 111, german_word: "Bruder", article: "der", english_translation: "brother", word_type: "noun", level: "A1", example_sentence_de: "Mein Bruder ist 12 Jahre alt.", example_sentence_en: "My brother is 12 years old." },
  { id: 112, german_word: "Schwester", article: "die", english_translation: "sister", word_type: "noun", level: "A1", example_sentence_de: "Meine Schwester studiert Medizin.", example_sentence_en: "My sister studies medicine." },
  // A1 - Places
  { id: 113, german_word: "Haus", article: "das", english_translation: "house", word_type: "noun", level: "A1", example_sentence_de: "Wir wohnen in einem großen Haus.", example_sentence_en: "We live in a big house." },
  { id: 114, german_word: "Schule", article: "die", english_translation: "school", word_type: "noun", level: "A1", example_sentence_de: "Die Kinder gehen jeden Tag in die Schule.", example_sentence_en: "The children go to school every day." },
  { id: 115, german_word: "Supermarkt", article: "der", english_translation: "supermarket", word_type: "noun", level: "A1", example_sentence_de: "Ich kaufe Brot im Supermarkt.", example_sentence_en: "I buy bread at the supermarket." },
  // A1 - Food & Drink
  { id: 116, german_word: "Wasser", article: "das", english_translation: "water", word_type: "noun", level: "A1", example_sentence_de: "Ich trinke gern Wasser.", example_sentence_en: "I like to drink water." },
  { id: 117, german_word: "Brot", article: "das", english_translation: "bread", word_type: "noun", level: "A1", example_sentence_de: "Zum Frühstück esse ich Brot.", example_sentence_en: "I eat bread for breakfast." },
  { id: 118, german_word: "Kaffee", article: "der", english_translation: "coffee", word_type: "noun", level: "A1", example_sentence_de: "Jeden Morgen trinke ich einen Kaffee.", example_sentence_en: "Every morning I drink a coffee." },
  { id: 119, german_word: "essen", english_translation: "to eat", word_type: "verb", level: "A1", example_sentence_de: "Was möchtest du essen?", example_sentence_en: "What would you like to eat?" },
  { id: 120, german_word: "trinken", english_translation: "to drink", word_type: "verb", level: "A1", example_sentence_de: "Ich trinke jeden Tag Tee.", example_sentence_en: "I drink tea every day." },
  // A1 - Verbs
  { id: 121, german_word: "gehen", english_translation: "to go / to walk", word_type: "verb", level: "A1", example_sentence_de: "Wir gehen heute ins Kino.", example_sentence_en: "We are going to the cinema today." },
  { id: 122, german_word: "kommen", english_translation: "to come", word_type: "verb", level: "A1", example_sentence_de: "Woher kommst du?", example_sentence_en: "Where do you come from?" },
  { id: 123, german_word: "sprechen", english_translation: "to speak", word_type: "verb", level: "A1", example_sentence_de: "Sprichst du Englisch?", example_sentence_en: "Do you speak English?" },
  { id: 124, german_word: "lernen", english_translation: "to learn", word_type: "verb", level: "A1", example_sentence_de: "Ich lerne jeden Tag Vokabeln.", example_sentence_en: "I learn vocabulary every day." },
  { id: 125, german_word: "wohnen", english_translation: "to live / to reside", word_type: "verb", level: "A1", example_sentence_de: "Ich wohne in München.", example_sentence_en: "I live in Munich." },
  // A1 - Adjectives
  { id: 126, german_word: "groß", english_translation: "big / tall", word_type: "adjective", level: "A1", example_sentence_de: "Berlin ist eine große Stadt.", example_sentence_en: "Berlin is a big city." },
  { id: 127, german_word: "klein", english_translation: "small / short", word_type: "adjective", level: "A1", example_sentence_de: "Das Kind ist noch sehr klein.", example_sentence_en: "The child is still very small." },
  { id: 128, german_word: "gut", english_translation: "good", word_type: "adjective", level: "A1", example_sentence_de: "Das Essen schmeckt sehr gut.", example_sentence_en: "The food tastes very good." },
  // A2 - Work & Education
  { id: 201, german_word: "Arbeit", article: "die", english_translation: "work / job", word_type: "noun", level: "A2", example_sentence_de: "Meine Arbeit beginnt um 8 Uhr.", example_sentence_en: "My work starts at 8 o'clock." },
  { id: 202, german_word: "Büro", article: "das", english_translation: "office", word_type: "noun", level: "A2", example_sentence_de: "Ich arbeite im Büro.", example_sentence_en: "I work in the office." },
  { id: 203, german_word: "Kollege", article: "der", english_translation: "colleague (male)", word_type: "noun", level: "A2", example_sentence_de: "Mein Kollege heißt Markus.", example_sentence_en: "My colleague's name is Markus." },
  { id: 204, german_word: "Termin", article: "der", english_translation: "appointment", word_type: "noun", level: "A2", example_sentence_de: "Ich habe morgen einen Termin beim Arzt.", example_sentence_en: "I have a doctor's appointment tomorrow." },
  // A2 - Travel & Transport
  { id: 205, german_word: "Bahnhof", article: "der", english_translation: "train station", word_type: "noun", level: "A2", example_sentence_de: "Der Zug fährt vom Bahnhof ab.", example_sentence_en: "The train departs from the train station." },
  { id: 206, german_word: "Flugzeug", article: "das", english_translation: "airplane", word_type: "noun", level: "A2", example_sentence_de: "Wir fliegen mit dem Flugzeug nach London.", example_sentence_en: "We fly to London by plane." },
  { id: 207, german_word: "Ticket", article: "das", english_translation: "ticket", word_type: "noun", level: "A2", example_sentence_de: "Kann ich ein Ticket kaufen?", example_sentence_en: "Can I buy a ticket?" },
  { id: 208, german_word: "reisen", english_translation: "to travel", word_type: "verb", level: "A2", example_sentence_de: "Im Sommer möchte ich nach Italien reisen.", example_sentence_en: "In summer I would like to travel to Italy." },
  { id: 209, german_word: "buchen", english_translation: "to book / reserve", word_type: "verb", level: "A2", example_sentence_de: "Ich möchte ein Hotelzimmer buchen.", example_sentence_en: "I would like to book a hotel room." },
  // A2 - Health
  { id: 210, german_word: "Arzt", article: "der", english_translation: "doctor (male)", word_type: "noun", level: "A2", example_sentence_de: "Der Arzt untersucht den Patienten.", example_sentence_en: "The doctor examines the patient." },
  { id: 211, german_word: "Krankenhaus", article: "das", english_translation: "hospital", word_type: "noun", level: "A2", example_sentence_de: "Er liegt im Krankenhaus.", example_sentence_en: "He is in the hospital." },
  { id: 212, german_word: "Schmerzen", english_translation: "pain / aches", word_type: "noun", level: "A2", example_sentence_de: "Ich habe Kopfschmerzen.", example_sentence_en: "I have a headache." },
  { id: 213, german_word: "gesund", english_translation: "healthy", word_type: "adjective", level: "A2", example_sentence_de: "Sport ist gesund.", example_sentence_en: "Sport is healthy." },
  // A2 - Shopping
  { id: 214, german_word: "kaufen", english_translation: "to buy", word_type: "verb", level: "A2", example_sentence_de: "Wo kann ich eine Zeitung kaufen?", example_sentence_en: "Where can I buy a newspaper?" },
  { id: 215, german_word: "bezahlen", english_translation: "to pay", word_type: "verb", level: "A2", example_sentence_de: "Kann ich mit Kreditkarte bezahlen?", english_translation: "Can I pay by credit card?" } as Vocabulary,
  { id: 216, german_word: "Rechnung", article: "die", english_translation: "bill / invoice", word_type: "noun", level: "A2", example_sentence_de: "Die Rechnung, bitte!", example_sentence_en: "The bill, please!" },
  { id: 217, german_word: "billig", english_translation: "cheap / inexpensive", word_type: "adjective", level: "A2", example_sentence_de: "Das T-Shirt ist sehr billig.", example_sentence_en: "The T-shirt is very cheap." },
  { id: 218, german_word: "teuer", english_translation: "expensive", word_type: "adjective", level: "A2", example_sentence_de: "Das Auto ist zu teuer.", example_sentence_en: "The car is too expensive." },
  // B1 - Society & Abstract
  { id: 301, german_word: "Gesellschaft", article: "die", english_translation: "society", word_type: "noun", level: "B1", example_sentence_de: "Die moderne Gesellschaft verändert sich schnell.", example_sentence_en: "Modern society is changing quickly." },
  { id: 302, german_word: "Umwelt", article: "die", english_translation: "environment", word_type: "noun", level: "B1", example_sentence_de: "Wir müssen die Umwelt schützen.", example_sentence_en: "We must protect the environment." },
  { id: 303, german_word: "Verantwortung", article: "die", english_translation: "responsibility", word_type: "noun", level: "B1", example_sentence_de: "Wir tragen Verantwortung für die Zukunft.", example_sentence_en: "We bear responsibility for the future." },
  { id: 304, german_word: "Ausbildung", article: "die", english_translation: "training / vocational education", word_type: "noun", level: "B1", example_sentence_de: "Er macht eine Ausbildung als Elektriker.", example_sentence_en: "He is doing a vocational training as an electrician." },
  { id: 305, german_word: "Erfahrung", article: "die", english_translation: "experience", word_type: "noun", level: "B1", example_sentence_de: "Sie hat viel Erfahrung in diesem Beruf.", example_sentence_en: "She has a lot of experience in this profession." },
  // B1 - Verbs
  { id: 306, german_word: "erklären", english_translation: "to explain", word_type: "verb", level: "B1", example_sentence_de: "Können Sie das noch einmal erklären?", example_sentence_en: "Can you explain that again?" },
  { id: 307, german_word: "beschreiben", english_translation: "to describe", word_type: "verb", level: "B1", example_sentence_de: "Bitte beschreiben Sie das Problem genau.", example_sentence_en: "Please describe the problem exactly." },
  { id: 308, german_word: "verbesssern", english_translation: "to improve", word_type: "verb", level: "B1", example_sentence_de: "Ich möchte mein Deutsch verbessern.", example_sentence_en: "I would like to improve my German." },
  { id: 309, german_word: "vorschlagen", english_translation: "to suggest / propose", word_type: "verb", level: "B1", example_sentence_de: "Ich möchte einen Kompromiss vorschlagen.", example_sentence_en: "I would like to suggest a compromise." },
  { id: 310, german_word: "sich bewerben", english_translation: "to apply (for a job)", word_type: "verb", level: "B1", example_sentence_de: "Ich möchte mich für diese Stelle bewerben.", example_sentence_en: "I would like to apply for this position." },
  // B1 - Adjectives
  { id: 311, german_word: "notwendig", english_translation: "necessary", word_type: "adjective", level: "B1", example_sentence_de: "Es ist notwendig, regelmäßig zu üben.", example_sentence_en: "It is necessary to practice regularly." },
  { id: 312, german_word: "bedeutend", english_translation: "significant / important", word_type: "adjective", level: "B1", example_sentence_de: "Das ist eine bedeutende Entscheidung.", example_sentence_en: "That is a significant decision." },
];

export const COURSES_FALLBACK: Course[] = [
  {
    id: 1,
    title: "Goethe A1 — Foundation German",
    slug: "goethe-a1-foundation",
    description: "Start your German journey from zero. Master everyday expressions, introductions, numbers, family, food, and basic grammar — everything you need for the Goethe A1 certificate.",
    level: "A1",
    is_premium: false,
    total_lessons: 12,
    estimated_hours: 20,
    xp_reward: 500,
    tags: ["Beginner", "A1", "Goethe", "Grammar", "Vocabulary"],
  },
  {
    id: 2,
    title: "Goethe A2 — Everyday German",
    slug: "goethe-a2-everyday",
    description: "Build confidence to navigate daily life in German — work, travel, health, shopping, and social situations. Includes all grammar patterns tested in the A2 Goethe exam.",
    level: "A2",
    is_premium: false,
    total_lessons: 16,
    estimated_hours: 30,
    xp_reward: 750,
    tags: ["Elementary", "A2", "Goethe", "Travel", "Work", "Health"],
  },
  {
    id: 3,
    title: "Goethe B1 — Independent German",
    slug: "goethe-b1-independent",
    description: "Reach independence in German. Engage in complex discussions about society, environment, and career. Full preparation for all 4 sections of the Goethe B1 exam.",
    level: "B1",
    is_premium: false,
    total_lessons: 20,
    estimated_hours: 40,
    xp_reward: 1000,
    tags: ["Intermediate", "B1", "Goethe", "Society", "Career", "Exam Prep"],
  },
];

export const FLASHCARDS_FALLBACK: Flashcard[] = [
  { id: 1001, front_text: "Guten Morgen!", back_text: "Good morning!", card_type: "phrase", level: "A1", hint: "Morning greeting" },
  { id: 1002, front_text: "Wie heißt du?", back_text: "What is your name?", card_type: "phrase", level: "A1" },
  { id: 1003, front_text: "Ich komme aus...", back_text: "I come from...", card_type: "phrase", level: "A1", hint: "Use to say your country of origin" },
  { id: 1004, front_text: "der, die, das — what do they mean?", back_text: "The (masculine, feminine, neuter) — German definite articles", card_type: "grammar", level: "A1" },
  { id: 1005, front_text: "Wie viel kostet das?", back_text: "How much does that cost?", card_type: "phrase", level: "A1" },
  { id: 1006, front_text: "das Essen", back_text: "the food / the meal", card_type: "vocabulary", level: "A1", hint: "neuter noun" },
  { id: 1007, front_text: "Ich möchte...", back_text: "I would like... (polite form of wollen)", card_type: "phrase", level: "A1" },
  { id: 1008, front_text: "Entschuldigung!", back_text: "Excuse me! / Sorry!", card_type: "phrase", level: "A1" },
  { id: 1009, front_text: "Wo ist die Toilette?", back_text: "Where is the toilet/bathroom?", card_type: "phrase", level: "A1" },
  { id: 1010, front_text: "Perfect Tense formula", back_text: "haben/sein + Partizip II at end\nEx: Ich habe gegessen. / Ich bin gegangen.", card_type: "grammar", level: "A2" },
  { id: 1011, front_text: "Können Sie mir helfen?", back_text: "Can you help me? (formal)", card_type: "phrase", level: "A2", hint: "Use 'können' + Sie for polite requests" },
  { id: 1012, front_text: "der Bahnhof", back_text: "the train station", card_type: "vocabulary", level: "A2", hint: "masculine noun — der" },
  { id: 1013, front_text: "Modal verb: müssen", back_text: "must / have to\nich muss · du musst · er muss · wir müssen", card_type: "grammar", level: "A2" },
  { id: 1014, front_text: "Ich habe einen Termin.", back_text: "I have an appointment.", card_type: "phrase", level: "A2" },
  { id: 1015, front_text: "Wie lange dauert das?", back_text: "How long does that take?", card_type: "phrase", level: "A2" },
  { id: 1016, front_text: "Dative prepositions", back_text: "aus · bei · mit · nach · seit · von · zu · gegenüber · außer\n(always dative!)", card_type: "grammar", level: "A2" },
  { id: 1017, front_text: "weil (subordinating conjunction)", back_text: "'because' — verb goes to the END\nEx: Ich lerne Deutsch, weil ich in Deutschland arbeiten möchte.", card_type: "grammar", level: "A2" },
  { id: 1018, front_text: "Ich würde gern...", back_text: "I would like to... (Konjunktiv II — polite/hypothetical)", card_type: "phrase", level: "B1" },
  { id: 1019, front_text: "Passive voice formation", back_text: "werden + Partizip II\nEx: Das Haus wird gebaut. (The house is being built.)", card_type: "grammar", level: "B1" },
  { id: 1020, front_text: "die Umwelt", back_text: "the environment", card_type: "vocabulary", level: "B1", hint: "Key B1 topic: Umweltschutz (environmental protection)" },
  { id: 1021, front_text: "Relative clause word order", back_text: "Noun + [, relative pronoun + ... + VERB (end)]\nEx: Der Mann, der Deutsch spricht, ist mein Lehrer.", card_type: "grammar", level: "B1" },
  { id: 1022, front_text: "Ich bin anderer Meinung.", back_text: "I have a different opinion. / I disagree.", card_type: "phrase", level: "B1", hint: "Useful in Sprechen exam discussions" },
  { id: 1023, front_text: "Einerseits... andererseits...", back_text: "On the one hand... on the other hand...", card_type: "phrase", level: "B1", hint: "Use this in Schreiben to show balanced argument" },
  { id: 1024, front_text: "obwohl (subordinating conjunction)", back_text: "'although' — verb goes to END\nEx: Obwohl es regnet, gehe ich spazieren.", card_type: "grammar", level: "B1" },
  { id: 1025, front_text: "Könnten Sie bitte...?", back_text: "Could you please...? (very polite request — Konjunktiv II)", card_type: "phrase", level: "B1", hint: "Essential for formal Schreiben tasks" },
];
